import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "造市商帳戶下單",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="zh-tw">
            <body className={inter.className}>
                <AntdRegistry>
                    <ConfigProvider
                        theme={{
                            token: {
                                colorPrimary: "#26C99B",
                                controlItemHoverBg: "#1DA57A",
                            },
                        }}
                    >
                        {children}
                    </ConfigProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
